#!/bin/bash
# Install Chrome.
sudo curl -sS -o - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add
sudo su -c "echo 'deb http://dl.google.com/linux/chrome/deb/ stable main' >> /etc/apt/sources.list.d/google-chrome.list"
# Update our system
sudo apt-get -y update
# Install Chrome
sudo apt-get -y install google-chrome-stable
# Install Chromedriver
wget -N 	https://storage.googleapis.com/chrome-for-testing-public/123.0.6312.86/linux64/chromedriver-linux64.zip -P ~/
unzip ~/chromedriver-linux64.zip -d ~/
# Remove zip file
rm ~/chromedriver-linux64.zip
# Move driver to bin location
sudo mv -f ~/chromedriver-linux64 /usr/local/bin/chromedriver
# Give it rights
sudo chown root:root /usr/local/bin/chromedriver
sudo chmod 0755 /usr/local/bin/chromedriver
# Adding Chrome Driver Path
echo 'export PATH=$PATH:/usr/local/bin/chromedriver' >> ~/.bash_profile
source ~/.bash_profile

